# Generated by Django 3.1.2 on 2020-11-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201115_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bod_y',
            new_name='comment',
        ),
    ]
